# Generated by Django 4.1 on 2023-12-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fortune_teller",
            "0002_fortune_sex_fortune_title_fortune_zodiac_sign_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fortune",
            name="text",
            field=models.TextField(max_length=1000),
        ),
    ]
