# Generated by Django 4.1 on 2024-01-09 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fortune_teller", "0005_remove_userprofile_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FortuneHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "fortune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fortune_teller.fortune",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
