# Generated by Django 4.1 on 2024-01-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fortune_teller", "0006_fortunehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
