# Generated by Django 4.1 on 2024-01-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fortune_teller", "0007_userprofile_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fortune",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="fortunehistory",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
